name: ❓ Ask a question
description: Submit a question to get help or clarification 🙋‍♂️
title: "[QUESTION]: "
labels: ["question"]
assignees:
  - YisusChrist
body:
  - type: markdown
    attributes:
      value: |
        ## Self Check
        - Check the [documentation](../wiki) and [GitHub Issues](../issues?q=is%3Aissue) to see if your question has already been answered.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Question
      description: Clearly state your question.
      placeholder: "What is the purpose of the this tool?"
  - type: textarea
    validations:
      required: true
    attributes:
      label: Context
      description: |
        Provide any necessary context for your question. For example, explain the scenario or code that led to your question.
      placeholder: |
        I was trying to use the tool to solve a problem with the following code:
        ```python
        # code snippet here
        ```
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected outcome or clarification needed
      description: |
        What do you expect to achieve, or what specific clarification are you seeking?
      placeholder: |
        I expected the tool to return a different output.
        Can you clarify how the solver handles edge cases?
  - type: input
    validations:
      required: true
    attributes:
      label: OS / Linux distribution
      placeholder: Windows 10, Ubuntu 20.04, Arch Linux, macOS 10.15...
  - type: dropdown
    attributes:
      label: If using WSL on Windows, which version of WSL
      description: Run `wsl -l -v` to check.
      options:
        - WSL1
        - WSL2
  - type: input
    validations:
      required: true
    attributes:
      label: Program version
      description: Run with the argument -V to check.
      placeholder: "1.0"
  - type: textarea
    attributes:
      label: Additional context or resources
      description: Add any other context or references (e.g., links, code snippets) that may help in answering your question.
